apiVersion: v2
name: storage-providers
description: CERNBox Storage Providers based in Revad to connect oCIS to EOS
type: application
version: 0.0.2
appVersion: 0.0.1
home: https://cernbox.web.ch
source: https://github.com/cernbox/charts
dependencies:
- name: revad
  version: "1.2.3"
  repository: "https://cs3org.github.io/charts"
  alias: home
  condition: home.enabled
- name: revad
  version: "1.2.3"
  repository: "https://cs3org.github.io/charts"
  alias: users
  condition: users.enabled
- name: revad
  version: "1.2.3"
  repository: "https://cs3org.github.io/charts"
  alias: shares
  condition: shares.enabled
maintainers:
  - name: SamuAlfageme
    email: samuel.alfageme.sainz@cern.ch
